services:
  # MongoDB Database
  mongodb:
    image: mongo:8.0.10
    container_name: webhook-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-noreyni}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-Password12345}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-webhook-db}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./logs/mongodb:/var/log/mongodb
    networks:
      - webhook-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_DATABASE:-webhook-db} --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: mongod --logpath /var/log/mongodb/mongod.log --logappend

  # Mongo Express - Web-based MongoDB admin interface
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: webhook-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      # MongoDB connection using environment variables
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-noreyni}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-Password12345}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017

      # Mongo Express authentication
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

      # UI Configuration
      ME_CONFIG_SITE_BASEURL: /
      ME_CONFIG_SITE_COOKIESECRET: noreyni-cookie-secret
      ME_CONFIG_SITE_SESSIONSECRET: noreyni-session-secret

      # Database settings
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER:-noreyni}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD:-Password12345}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - webhook-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes for data persistence
volumes:
  mongodb_data:
    driver: local
    name: webhook_mongodb_data
  mongodb_config:
    driver: local
    name: webhook_mongodb_config

# Custom network for service communication
networks:
  webhook-network:
    driver: bridge
    name: webhook-network